#include <iostream> 
#include <bits/stdc++.h>
#include <fstream>
#include <cstring>  
#include <cstdio>
#include <iomanip>
#include <cstdlib>
#include <cmath>
#include <sys/time.h>
#include <time.h>
#include <gmpxx.h>
#include <vector>
#include <string>
#include <math.h>
